## Deep Learning, DL Models, and Applications

```python
# Task 6: Bidirectional Long Short-Term Memory (BiLSTM) Cell
# Mechanics from Scratch
# ● Objective: Learn sequence transduction architectures and dynamic temporal tracking by
# implementing gated recurrent equations and memory routing layouts from scratch.
# ● Required Tech Stack: PyTorch (Tensor operations only, no nn.RNN or nn.LSTM), NumPy.
# ● Task Description: Students will design and execute a bidirectional LSTM layer. They must
# write individual loop-based step updates calculating Input ( ), Forget ( ), Output ( ),
# and Cell State Candidate ( ) activations, stitc
```

In [141]:
#Step 1: Import Libraries
import torch
import numpy as np

torch.manual_seed(42)

In [142]:
#Step 2: Create Sample Sequence
sequence = torch.randn(5,3)

print(sequence)


tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094],
        [ 1.1103, -1.6898, -0.9890]])


In [143]:
#Step 3: Initialize Weights
input_size = 3
hidden_size = 4

W_i = torch.randn(input_size+hidden_size, hidden_size)
W_f = torch.randn(input_size+hidden_size, hidden_size)
W_o = torch.randn(input_size+hidden_size, hidden_size)
W_g = torch.randn(input_size+hidden_size, hidden_size)

b_i = torch.zeros(hidden_size)
b_f = torch.zeros(hidden_size)
b_o = torch.zeros(hidden_size)
b_g = torch.zeros(hidden_size)



In [144]:
#Step 4: Activation Functions
def sigmoid(x):
    return 1 / (1 + torch.exp(-x))
def tanh(x):
    return torch.tanh(x)

In [145]:
def tanh(x):
    return torch.tanh(x)

In [146]:
#Step 5: LSTM Cell
def lstm_cell(x, h_prev, c_prev):

    combined = torch.cat((x, h_prev))

    i = sigmoid(combined @ W_i + b_i)

    f = sigmoid(combined @ W_f + b_f)

    o = sigmoid(combined @ W_o + b_o)

    g = tanh(combined @ W_g + b_g)

    c = f * c_prev + i * g

    h = o * tanh(c)

    return h, c

In [147]:
#Step 6: Forward LSTM
def forward_lstm(sequence):

    h = torch.zeros(hidden_size)

    c = torch.zeros(hidden_size)

    outputs = []

    for x in sequence:

        h, c = lstm_cell(x, h, c)

        outputs.append(h)

    return torch.stack(outputs)


In [148]:
forward_output = forward_lstm(sequence)

print(forward_output)

tensor([[-0.0251, -0.0246,  0.0717,  0.0624],
        [-0.1016,  0.0379, -0.0987, -0.3267],
        [-0.1522, -0.0318, -0.0676, -0.2509],
        [-0.1144, -0.0681,  0.0716, -0.2177],
        [-0.0703, -0.0229, -0.2675, -0.5455]])


In [150]:
#Step 7: Backward LSTM

# Process the sequence in reverse.

def backward_lstm(sequence):

    h = torch.zeros(hidden_size)

    c = torch.zeros(hidden_size)

    outputs = []

    for x in reversed(sequence):

        h, c = lstm_cell(x, h, c)

        outputs.append(h)

    outputs.reverse()

    return torch.stack(outputs)

In [151]:
backward_output = backward_lstm(sequence)

print(backward_output)

tensor([[-0.1888, -0.1497, -0.1148, -0.2262],
        [-0.0971, -0.0095, -0.1519, -0.5107],
        [-0.0231, -0.0363,  0.1576, -0.2363],
        [-0.0383, -0.3039,  0.1335, -0.0513],
        [ 0.0558, -0.0218, -0.4146, -0.4513]])


In [152]:
#Step 8: BiLSTM Output
bilstm_output = torch.cat(
    (forward_output, backward_output),
    dim=1
)

print(bilstm_output)

tensor([[-0.0251, -0.0246,  0.0717,  0.0624, -0.1888, -0.1497, -0.1148, -0.2262],
        [-0.1016,  0.0379, -0.0987, -0.3267, -0.0971, -0.0095, -0.1519, -0.5107],
        [-0.1522, -0.0318, -0.0676, -0.2509, -0.0231, -0.0363,  0.1576, -0.2363],
        [-0.1144, -0.0681,  0.0716, -0.2177, -0.0383, -0.3039,  0.1335, -0.0513],
        [-0.0703, -0.0229, -0.2675, -0.5455,  0.0558, -0.0218, -0.4146, -0.4513]])


In [153]:
print("Forward Output Shape:", forward_output.shape)

print("Backward Output Shape:", backward_output.shape)

print("BiLSTM Output Shape:", bilstm_output.shape)

Forward Output Shape: torch.Size([5, 4])
Backward Output Shape: torch.Size([5, 4])
BiLSTM Output Shape: torch.Size([5, 8])
