## Deep Learning, DL Models, and Applications

```python
# Task 5: Custom Batch Normalization and Layer Normalization
# Forward/Backward Propagation
# ● Objective: Maximize training convergence speeds and stabilize internal covariate shifts by
# building structural normalization layers with manual gradient derivations.
# ● Required Tech Stack: PyTorch (with Autograd disabled), NumPy.
# ● Task Description: Students must write functional modules for Batch Normalization and
# Layer Normalization. They are required to derive and implement the forward passes
# (calculating running mean and variance) and write the exact partial derivatives for
# backpropagating gradients through the scale parameter , shift parameter , and
# normalize transformations.
```

In [110]:
#Step 1: Import Libraries
import torch
import numpy as np

torch.manual_seed(42)

In [111]:
#Step 2: Create Sample Data
X = torch.randn(4, 3)

print(X)


tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094]])


In [112]:
#Step 3: Batch Normalization (Forward)
def batch_norm_forward(X, gamma, beta, eps=1e-5):

    mean = X.mean(dim=0, keepdim=True)

    var = X.var(dim=0, unbiased=False, keepdim=True)

    X_norm = (X - mean) / torch.sqrt(var + eps)

    out = gamma * X_norm + beta

    return out, X_norm

In [113]:
gamma = torch.ones(1, 3)

beta = torch.zeros(1, 3)

In [114]:
output_bn, X_norm_bn = batch_norm_forward(X, gamma, beta)

print(output_bn)

tensor([[-0.5067,  0.6239, -0.2637],
        [-0.6339, -1.3134, -1.4275],
        [ 1.7302, -0.5630,  0.3647],
        [-0.5896,  1.2525,  1.3264]])


In [115]:
#Step 4: Layer Normalization (Forward)
def layer_norm_forward(X, gamma, beta, eps=1e-5):

    mean = X.mean(dim=1, keepdim=True)

    var = X.var(dim=1, unbiased=False, keepdim=True)

    X_norm = (X - mean) / torch.sqrt(var + eps)

    out = gamma * X_norm + beta

    return out, X_norm

In [116]:
output_ln, X_norm_ln = layer_norm_forward(X, gamma, beta)

print(output_ln)

tensor([[ 1.2171, -1.2306,  0.0134],
        [ 1.0426, -1.3488,  0.3062],
        [ 1.3063, -1.1223, -0.1840],
        [-1.2194, -0.0104,  1.2298]])


In [117]:
#Step 5: Manual Backward Pass
dout = torch.ones_like(output_bn)

In [118]:
def backward(dout, X_norm):

    dgamma = (dout * X_norm).sum(dim=0, keepdim=True)

    dbeta = dout.sum(dim=0, keepdim=True)

    return dgamma, dbeta


In [119]:
dgamma, dbeta = backward(dout, X_norm_bn)

print("dgamma:")
print(dgamma)

print()

print("dbeta:")
print(dbeta)

dgamma:
tensor([[-5.9605e-08,  0.0000e+00, -1.1921e-07]])

dbeta:
tensor([[4., 4., 4.]])


In [120]:
#Step 6: Test LayerNorm Backward
dgamma_ln, dbeta_ln = backward(dout, X_norm_ln)

print(dgamma_ln)

print(dbeta_ln)

tensor([[ 2.3466, -3.7121,  1.3655]])
tensor([[4., 4., 4.]])
